module_label('0 read')
module_menu('   png','modules/0%20read/png')
module_menu('   stl','modules/0%20read/stl')
module_menu('   svg','modules/0%20read/svg')
module_menu('   text','modules/0%20read/text')
module_label('1 path')
module_label('   1.1 machines')
module_label('      large CNC')
module_menu('         ShopBot','modules/1%20path/1.1%20machines/large%20CNC/ShopBot')
module_label('      laser cutter')
module_menu('         Epilog','modules/1%20path/1.1%20machines/laser%20cutter/Epilog')
module_menu('         Trotec','modules/1%20path/1.1%20machines/laser%20cutter/Trotec')
module_label('      precision mill')
module_menu('         Roland MDX-20','modules/1%20path/1.1%20machines/precision%20mill/Roland%20MDX-20')
module_menu('         Roland MDX-20 Move Beta','modules/1%20path/1.1%20machines/precision%20mill/Roland%20MDX-20%20Move%20Beta')
module_menu('         Roland SRM-20','modules/1%20path/1.1%20machines/precision%20mill/Roland%20SRM-20')
module_label('      vinyl cutter')
module_menu('         Roland GX-GS-24','modules/1%20path/1.1%20machines/vinyl%20cutter/Roland%20GX-GS-24')
module_label('   1.2 formats')
module_menu('      dxf','modules/1%20path/1.2%20formats/dxf')
module_menu('      g-code','modules/1%20path/1.2%20formats/g-code')
module_menu('      svg','modules/1%20path/1.2%20formats/svg')
module_label('   1.3 view')
module_menu('      view','modules/1%20path/1.3%20view/view')
module_label('2 file')
module_menu('   save','modules/2%20file/save')
module_label('3 socket')
module_label('   server')
module_menu('      device','modules/3%20socket/server/device')
module_menu('      echo','modules/3%20socket/server/echo')
module_menu('      print','modules/3%20socket/server/print')
module_menu('      serial','modules/3%20socket/server/serial')
module_menu('      serialpy','modules/3%20socket/server/serialpy')
module_menu('      udp','modules/3%20socket/server/udp')
module_menu('   websocket','modules/3%20socket/websocket')
module_label('4 ui')
module_menu('   bar graph','modules/4%20ui/bar%20graph')
module_menu('   button window','modules/4%20ui/button%20window')
module_menu('   color','modules/4%20ui/color')
module_menu('   label','modules/4%20ui/label')
module_menu('   note','modules/4%20ui/note')
module_menu('   slider','modules/4%20ui/slider')
module_menu('   text window','modules/4%20ui/text%20window')
module_label('5 image')
module_menu('   boundingbox','modules/5%20image/boundingbox')
module_menu('   color separation','modules/5%20image/color%20separation')
module_menu('   distance transform','modules/5%20image/distance%20transform')
module_menu('   dogbone','modules/5%20image/dogbone')
module_menu('   edge detect','modules/5%20image/edge%20detect')
module_menu('   function','modules/5%20image/function')
module_menu('   motion detect','modules/5%20image/motion%20detect')
module_menu('   offset','modules/5%20image/offset')
module_menu('   orient edges','modules/5%20image/orient%20edges')
module_menu('   palette','modules/5%20image/palette')
module_menu('   raster mask','modules/5%20image/raster%20mask')
module_menu('   size','modules/5%20image/size')
module_menu('   threshold','modules/5%20image/threshold')
module_menu('   vector mask','modules/5%20image/vector%20mask')
module_menu('   vectorize','modules/5%20image/vectorize')
module_label('6 frep')
module_label('   operators')
module_menu('      add','modules/6%20frep/operators/add')
module_menu('      blend','modules/6%20frep/operators/blend')
module_menu('      clearance','modules/6%20frep/operators/clearance')
module_menu('      intersect','modules/6%20frep/operators/intersect')
module_menu('      morph','modules/6%20frep/operators/morph')
module_menu('      subtract','modules/6%20frep/operators/subtract')
module_label('   shapes 2D')
module_menu('      arc','modules/6%20frep/shapes%202D/arc')
module_menu('      circle','modules/6%20frep/shapes%202D/circle')
module_menu('      function','modules/6%20frep/shapes%202D/function')
module_menu('      involute gear','modules/6%20frep/shapes%202D/involute%20gear')
module_menu('      involute rack','modules/6%20frep/shapes%202D/involute%20rack')
module_menu('      polygon','modules/6%20frep/shapes%202D/polygon')
module_menu('      rectangle','modules/6%20frep/shapes%202D/rectangle')
module_menu('      right triangle','modules/6%20frep/shapes%202D/right%20triangle')
module_menu('      triangle','modules/6%20frep/shapes%202D/triangle')
module_label('   shapes 3D')
module_menu('      cone','modules/6%20frep/shapes%203D/cone')
module_menu('      cube','modules/6%20frep/shapes%203D/cube')
module_menu('      cylinder','modules/6%20frep/shapes%203D/cylinder')
module_menu('      function','modules/6%20frep/shapes%203D/function')
module_menu('      lattice','modules/6%20frep/shapes%203D/lattice')
module_menu('      menger','modules/6%20frep/shapes%203D/menger')
module_menu('      pyramid','modules/6%20frep/shapes%203D/pyramid')
module_menu('      sphere','modules/6%20frep/shapes%203D/sphere')
module_menu('      torus','modules/6%20frep/shapes%203D/torus')
module_label('   transforms')
module_menu('      extrude','modules/6%20frep/transforms/extrude')
module_menu('      inflate','modules/6%20frep/transforms/inflate')
module_menu('      reflect','modules/6%20frep/transforms/reflect')
module_menu('      repeat linear','modules/6%20frep/transforms/repeat%20linear')
module_menu('      repeat rotary','modules/6%20frep/transforms/repeat%20rotary')
module_menu('      revolve','modules/6%20frep/transforms/revolve')
module_menu('      rotate','modules/6%20frep/transforms/rotate')
module_menu('      scale','modules/6%20frep/transforms/scale')
module_menu('      shear','modules/6%20frep/transforms/shear')
module_menu('      shell','modules/6%20frep/transforms/shell')
module_menu('      slice','modules/6%20frep/transforms/slice')
module_menu('      taper','modules/6%20frep/transforms/taper')
module_menu('      translate','modules/6%20frep/transforms/translate')
module_label('   view')
module_menu('      render (CPU)','modules/6%20frep/view/render%20(CPU)')
module_menu('      render (GPU)','modules/6%20frep/view/render%20(GPU)')
module_menu('      slice','modules/6%20frep/view/slice')
module_label('7 defaults')
module_menu('   Othermill defaults','modules/7%20defaults/Othermill%20defaults')
module_menu('   Roland Mill defaults','modules/7%20defaults/Roland%20Mill%20defaults')
module_label('character')
module_menu('   convert','modules/character/convert')
module_menu('   in out','modules/character/in%20out')
module_menu('   parse','modules/character/parse')
module_menu('   variable','modules/character/variable')
module_label('connect')
module_label('   svg')
module_menu('      ExtractFaces','modules/connect/svg/ExtractFaces')
module_menu('      PCB','modules/connect/svg/PCB')
module_menu('      SelectFace','modules/connect/svg/SelectFace')
module_label('convert')
module_label('   rgba')
module_menu('      jpg','modules/convert/rgba/jpg')
module_menu('      png','modules/convert/rgba/png')
module_label('   svg')
module_menu('      array','modules/convert/svg/array')
module_menu('      image','modules/convert/svg/image')
module_label('dev')
module_menu('   log','modules/dev/log')
module_label('event')
module_menu('   delay','modules/event/delay')
module_menu('   generate','modules/event/generate')
module_menu('   pause','modules/event/pause')
module_menu('   sequence','modules/event/sequence')
module_label('input')
module_menu('   video','modules/input/video')
module_label('iterate')
module_menu('   step','modules/iterate/step')
module_menu('   step and delay','modules/iterate/step%20and%20delay')
module_label('library')
module_menu('   globals','modules/library/globals')
module_menu('   library','modules/library/library')
module_menu('   three.js','modules/library/three.js')
module_label('math')
module_menu('   benchmark','modules/math/benchmark')
module_menu('   dyadic','modules/math/dyadic')
module_menu('   glsl_benchmark','modules/math/glsl_benchmark')
module_menu('   parallel','modules/math/parallel')
module_menu('   scalar','modules/math/scalar')
module_label('mesh')
module_menu('   height map','modules/mesh/height%20map')
module_menu('   rotate','modules/mesh/rotate')
module_menu('   slice raster','modules/mesh/slice%20raster')
module_label('module')
module_menu('   create','modules/module/create')
module_menu('   delete','modules/module/delete')
module_menu('   move','modules/module/move')
module_label('network')
module_menu('   apa','modules/network/apa')
module_label('object')
module_menu('   construct','modules/object/construct')
module_menu('   download','modules/object/download')
module_menu('   set','modules/object/set')
module_menu('   string','modules/object/string')
module_menu('   view','modules/object/view')
module_label('processes')
module_label('   cut')
module_menu('      raster','modules/processes/cut/raster')
module_label('   mill')
module_label('      raster')
module_menu('         2.5D','modules/processes/mill/raster/2.5D')
module_menu('         2D','modules/processes/mill/raster/2D')
module_label('string')
module_menu('   format','modules/string/format')
module_menu('   variables','modules/string/variables')

