module_label('0 read')
module_menu(' png.js','modules/0%20read/png.js')
module_menu(' stl.js','modules/0%20read/stl.js')
module_menu(' svg.js','modules/0%20read/svg.js')
module_menu(' text.js','modules/0%20read/text.js')
module_label('1 path')
module_label(' 1.1 machines')
module_label('  large CNC')
module_menu('   ShopBot.js','modules/1%20path/1.1%20machines/large%20CNC/ShopBot.js')
module_label('  laser cutter')
module_menu('   Epilog.js','modules/1%20path/1.1%20machines/laser%20cutter/Epilog.js')
module_menu('   Trotec.js','modules/1%20path/1.1%20machines/laser%20cutter/Trotec.js')
module_label('  precision mill')
module_menu('   Othermill-Bantam Tools.js','modules/1%20path/1.1%20machines/precision%20mill/Othermill-Bantam%20Tools.js')
module_menu('   Roland MDX-iModela.js','modules/1%20path/1.1%20machines/precision%20mill/Roland%20MDX-iModela.js')
module_menu('   Roland SRM-20 Relative.js','modules/1%20path/1.1%20machines/precision%20mill/Roland%20SRM-20%20Relative.js')
module_menu('   Roland SRM-20.js','modules/1%20path/1.1%20machines/precision%20mill/Roland%20SRM-20.js')
module_label('  vinyl cutter')
module_menu('   Cricut vinyl cutter.js','modules/1%20path/1.1%20machines/vinyl%20cutter/Cricut%20vinyl%20cutter.js')
module_menu('   GCC vinyl cutter.js','modules/1%20path/1.1%20machines/vinyl%20cutter/GCC%20vinyl%20cutter.js')
module_menu('   Roland GX-GS-24 Absolute.js','modules/1%20path/1.1%20machines/vinyl%20cutter/Roland%20GX-GS-24%20Absolute.js')
module_menu('   Roland GX-GS-24 Relative.js','modules/1%20path/1.1%20machines/vinyl%20cutter/Roland%20GX-GS-24%20Relative.js')
module_menu('   Silhouette Cameo 2.js','modules/1%20path/1.1%20machines/vinyl%20cutter/Silhouette%20Cameo%202.js')
module_menu('   Silhouette Cameo.js','modules/1%20path/1.1%20machines/vinyl%20cutter/Silhouette%20Cameo.js')
module_label(' 1.2 formats')
module_menu('  dxf','modules/1%20path/1.2%20formats/dxf')
module_menu('  g-code','modules/1%20path/1.2%20formats/g-code')
module_menu('  svg','modules/1%20path/1.2%20formats/svg')
module_label(' 1.3 view')
module_menu('  view toolpath','modules/1%20path/1.3%20view/view%20toolpath')
module_label('2 file')
module_menu(' save.js','modules/2%20file/save.js')
module_label('3 socket')
module_label(' server')
module_menu('  device.js','modules/3%20socket/server/device.js')
module_menu('  echo.js','modules/3%20socket/server/echo.js')
module_menu('  print.js','modules/3%20socket/server/print.js')
module_menu('  pyserial.js','modules/3%20socket/server/pyserial.js')
module_menu('  serial.js','modules/3%20socket/server/serial.js')
module_menu('  udp.js','modules/3%20socket/server/udp.js')
module_menu(' websocket.js','modules/3%20socket/websocket.js')
module_label('4 ui')
module_menu(' bar graph.js','modules/4%20ui/bar%20graph.js')
module_menu(' button window.js','modules/4%20ui/button%20window.js')
module_menu(' color.js','modules/4%20ui/color.js')
module_menu(' label simple.js','modules/4%20ui/label%20simple.js')
module_menu(' label.js','modules/4%20ui/label.js')
module_menu(' note.js','modules/4%20ui/note.js')
module_menu(' slider.js','modules/4%20ui/slider.js')
module_menu(' text window.js','modules/4%20ui/text%20window.js')
module_label('5 image')
module_menu(' boundingbox.js','modules/5%20image/boundingbox.js')
module_menu(' color separation.js','modules/5%20image/color%20separation.js')
module_menu(' crop.js','modules/5%20image/crop.js')
module_menu(' distance transform.js','modules/5%20image/distance%20transform.js')
module_menu(' dogbone.js','modules/5%20image/dogbone.js')
module_menu(' edge detect.js','modules/5%20image/edge%20detect.js')
module_menu(' function.js','modules/5%20image/function.js')
module_menu(' motion detect.js','modules/5%20image/motion%20detect.js')
module_menu(' offset.js','modules/5%20image/offset.js')
module_menu(' orient edges.js','modules/5%20image/orient%20edges.js')
module_menu(' palette.js','modules/5%20image/palette.js')
module_menu(' raster mask.js','modules/5%20image/raster%20mask.js')
module_menu(' size.js','modules/5%20image/size.js')
module_menu(' threshold.js','modules/5%20image/threshold.js')
module_menu(' vector mask.js','modules/5%20image/vector%20mask.js')
module_menu(' vectorize.js','modules/5%20image/vectorize.js')
module_label('6 frep')
module_label(' operators')
module_menu('  add.js','modules/6%20frep/operators/add.js')
module_menu('  blend.js','modules/6%20frep/operators/blend.js')
module_menu('  clearance.js','modules/6%20frep/operators/clearance.js')
module_menu('  intersect.js','modules/6%20frep/operators/intersect.js')
module_menu('  morph.js','modules/6%20frep/operators/morph.js')
module_menu('  subtract.js','modules/6%20frep/operators/subtract.js')
module_label(' shapes 2D')
module_menu('  arc.js','modules/6%20frep/shapes%202D/arc.js')
module_menu('  circle.js','modules/6%20frep/shapes%202D/circle.js')
module_menu('  function.js','modules/6%20frep/shapes%202D/function.js')
module_menu('  involute gear.js','modules/6%20frep/shapes%202D/involute%20gear.js')
module_menu('  involute rack.js','modules/6%20frep/shapes%202D/involute%20rack.js')
module_menu('  polygon.js','modules/6%20frep/shapes%202D/polygon.js')
module_menu('  rectangle.js','modules/6%20frep/shapes%202D/rectangle.js')
module_menu('  right triangle.js','modules/6%20frep/shapes%202D/right%20triangle.js')
module_menu('  triangle.js','modules/6%20frep/shapes%202D/triangle.js')
module_label(' shapes 3D')
module_menu('  cone.js','modules/6%20frep/shapes%203D/cone.js')
module_menu('  cube.js','modules/6%20frep/shapes%203D/cube.js')
module_menu('  cylinder.js','modules/6%20frep/shapes%203D/cylinder.js')
module_menu('  function.js','modules/6%20frep/shapes%203D/function.js')
module_menu('  lattice.js','modules/6%20frep/shapes%203D/lattice.js')
module_menu('  menger.js','modules/6%20frep/shapes%203D/menger.js')
module_menu('  pyramid.js','modules/6%20frep/shapes%203D/pyramid.js')
module_menu('  sphere.js','modules/6%20frep/shapes%203D/sphere.js')
module_menu('  torus.js','modules/6%20frep/shapes%203D/torus.js')
module_label(' transforms')
module_menu('  extrude.js','modules/6%20frep/transforms/extrude.js')
module_menu('  inflate.js','modules/6%20frep/transforms/inflate.js')
module_menu('  reflect.js','modules/6%20frep/transforms/reflect.js')
module_menu('  repeat linear.js','modules/6%20frep/transforms/repeat%20linear.js')
module_menu('  repeat rotary.js','modules/6%20frep/transforms/repeat%20rotary.js')
module_menu('  revolve.js','modules/6%20frep/transforms/revolve.js')
module_menu('  rotate.js','modules/6%20frep/transforms/rotate.js')
module_menu('  scale.js','modules/6%20frep/transforms/scale.js')
module_menu('  shear.js','modules/6%20frep/transforms/shear.js')
module_menu('  shell.js','modules/6%20frep/transforms/shell.js')
module_menu('  slice.js','modules/6%20frep/transforms/slice.js')
module_menu('  taper.js','modules/6%20frep/transforms/taper.js')
module_menu('  translate.js','modules/6%20frep/transforms/translate.js')
module_label(' view')
module_menu('  render (CPU).js','modules/6%20frep/view/render%20(CPU).js')
module_menu('  render (GPU).js','modules/6%20frep/view/render%20(GPU).js')
module_menu('  slice.js','modules/6%20frep/view/slice.js')
module_label('7 defaults')
module_menu(' Othermill defaults.js','modules/7%20defaults/Othermill%20defaults.js')
module_menu(' PCB defaults.js','modules/7%20defaults/PCB%20defaults.js')
module_menu(' Roland Mill defaults.js','modules/7%20defaults/Roland%20Mill%20defaults.js')
module_label('character')
module_menu(' convert.js','modules/character/convert.js')
module_menu(' in out.js','modules/character/in%20out.js')
module_menu(' parse.js','modules/character/parse.js')
module_menu(' variable.js','modules/character/variable.js')
module_label('connect')
module_label(' stl')
module_menu('  STL.js','modules/connect/stl/STL.js')
module_label(' svg')
module_menu('  ExtractFaces.js','modules/connect/svg/ExtractFaces.js')
module_menu('  Honeycomb.js','modules/connect/svg/Honeycomb.js')
module_menu('  PCB.js','modules/connect/svg/PCB.js')
module_menu('  SelectFace.js','modules/connect/svg/SelectFace.js')
module_label('convert')
module_label(' rgba')
module_menu('  jpg.js','modules/convert/rgba/jpg.js')
module_menu('  png.js','modules/convert/rgba/png.js')
module_label(' svg')
module_menu('  array.js','modules/convert/svg/array.js')
module_menu('  image.js','modules/convert/svg/image.js')
module_label('dev')
module_menu(' log.js','modules/dev/log.js')
module_label('event')
module_menu(' delay.js','modules/event/delay.js')
module_menu(' generate.js','modules/event/generate.js')
module_menu(' pause.js','modules/event/pause.js')
module_menu(' sequence.js','modules/event/sequence.js')
module_label('input')
module_menu(' video.js','modules/input/video.js')
module_label('iterate')
module_menu(' step and delay.js','modules/iterate/step%20and%20delay.js')
module_menu(' step.js','modules/iterate/step.js')
module_label('library')
module_menu(' globals.js','modules/library/globals.js')
module_menu(' library.js','modules/library/library.js')
module_menu(' three.js','modules/library/three.js')
module_label('math')
module_menu(' benchmark.js','modules/math/benchmark.js')
module_menu(' dyadic.js','modules/math/dyadic.js')
module_menu(' glsl_benchmark.js','modules/math/glsl_benchmark.js')
module_menu(' parallel.js','modules/math/parallel.js')
module_menu(' scalar.js','modules/math/scalar.js')
module_label('mesh')
module_menu(' height map.js','modules/mesh/height%20map.js')
module_menu(' rotate.js','modules/mesh/rotate.js')
module_menu(' slice raster.js','modules/mesh/slice%20raster.js')
module_label('module')
module_menu(' blank.js','modules/module/blank.js')
module_menu(' create.js','modules/module/create.js')
module_menu(' delete.js','modules/module/delete.js')
module_menu(' move.js','modules/module/move.js')
module_label('network')
module_menu(' apa.js','modules/network/apa.js')
module_label('object')
module_menu(' construct.js','modules/object/construct.js')
module_menu(' download.js','modules/object/download.js')
module_menu(' set.js','modules/object/set.js')
module_menu(' string.js','modules/object/string.js')
module_menu(' view.js','modules/object/view.js')
module_label('processes')
module_label(' cut')
module_menu('  raster.js','modules/processes/cut/raster.js')
module_label(' mill')
module_label('  raster')
module_menu('   2.5D.js','modules/processes/mill/raster/2.5D.js')
module_menu('   2D.js','modules/processes/mill/raster/2D.js')
module_menu('   3D.js','modules/processes/mill/raster/3D.js')
module_label('string')
module_menu(' format.js','modules/string/format.js')
module_menu(' variables.js','modules/string/variables.js')

