#!/bin/bash
#
# start mods server
#
# Neil Gershenfeld 
# (c) Massachusetts Institute of Technology 2016
#
# Modified bt Francisco Sanchez Arroyo 2020
#
# This work may be reproduced, modified, distributed, performed, and 
# displayed for any purpose, but must acknowledge the fab modules 
# project. Copyright is retained and must be preserved. The work is 
# provided as is; no warranty is provided, and users accept all 
# liability.

#
# find path, following symlinks
#    from http://www.ostricher.com/2014/10/the-right-way-to-get-the-directory-of-a-bash-script/
#
get_script_dir () {
   SOURCE="${BASH_SOURCE[0]}"
   while [ -h "$SOURCE" ]; do
      DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
      SOURCE="$( readlink "$SOURCE" )"
      [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
   done
   DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
   echo "$DIR"
   }
path=$(get_script_dir)

#
# cd to script
#
cd $path
cd ..

#
# uncomment to start local http server (ignores error if already running)
#
http-server -p 8080 &
zenity --info --text 'webserver started http://127.0.0.1:8080'

#
# uncomment to start node print server (ignores error if already running)
# for printer permission:
#    sudo adduser user_name lp
#    sudo adduser user_name lpadmin
#
cd js
node printserver.js ::ffff:127.0.0.1 1234 &
zenity --info --text 'mods printserver started'
#
# uncomment to start node serial server (ignores error if already running)
# for serial permission:
#    sudo adduser user_name dialout
#
cd js
node serialserver.js ::ffff:127.0.0.1 1235 &
zenity --info --text 'mods serialserver started'

# uncomment to start node device server (ignores error if already running)
# for lp device permission:
#    sudo adduser user_name lp lpadmin
#
cd js
node deviceserver.js ::ffff:127.0.0.1 1236 &
zenity --info --text 'mods serialserver started'

