#!/bin/bash
#
# stop mods server
#
# Neil Gershenfeld 
# (c) Massachusetts Institute of Technology 2016
#
# This work may be reproduced, modified, distributed, performed, and 
# displayed for any purpose, but must acknowledge the fab modules 
# project. Copyright is retained and must be preserved. The work is 
# provided as is; no warranty is provided, and users accept all 
# liability.
#
pkill -f "node printserver.js"
pkill -f "node serialserver.js"
pkill -f "node deviceserver.js"
pkill -f "node udpserver.js"
pkill -f "node echoserver.js"
pkill -f "python3 serialserver.py"
pkill -f "http-server -a 127.0.0.1 -p 8080"
echo 'all mods servers stopped'

