program_label('1 machines')
program_label('   1.1 Roland')
program_label('      GX-GS 24 vinyl cutters')
program_menu('         cut','programs/1%20machines/1.1%20Roland/GX-GS%2024%20vinyl%20cutters/cut')
program_menu('         cut xDesign','programs/1%20machines/1.1%20Roland/GX-GS%2024%20vinyl%20cutters/cut%20xDesign')
program_label('      MDX-20 mill')
program_menu('         PCB','programs/1%20machines/1.1%20Roland/MDX-20%20mill/PCB')
program_label('      SRM-20 mill')
program_menu('         PCB png','programs/1%20machines/1.1%20Roland/SRM-20%20mill/PCB%20png')
program_menu('         PCB svg','programs/1%20machines/1.1%20Roland/SRM-20%20mill/PCB%20svg')
program_menu('         PCB svg connect','programs/1%20machines/1.1%20Roland/SRM-20%20mill/PCB%20svg%20connect')
program_label('   1.2 Epilog')
program_menu('      cut png','programs/1%20machines/1.2%20Epilog/cut%20png')
program_menu('      cut svg','programs/1%20machines/1.2%20Epilog/cut%20svg')
program_menu('      cut svg connect','programs/1%20machines/1.2%20Epilog/cut%20svg%20connect')
program_label('   1.3 Trotec')
program_menu('      cut','programs/1%20machines/1.3%20Trotec/cut')
program_label('   1.4 ShopBot')
program_menu('      mill 2.5D stl','programs/1%20machines/1.4%20ShopBot/mill%202.5D%20stl')
program_menu('      mill 2.5D stl connect','programs/1%20machines/1.4%20ShopBot/mill%202.5D%20stl%20connect')
program_menu('      mill 2D png','programs/1%20machines/1.4%20ShopBot/mill%202D%20png')
program_menu('      mill 2D png PCB','programs/1%20machines/1.4%20ShopBot/mill%202D%20png%20PCB')
program_menu('      mill 2D stl','programs/1%20machines/1.4%20ShopBot/mill%202D%20stl')
program_menu('      mill 2D svg','programs/1%20machines/1.4%20ShopBot/mill%202D%20svg')
program_menu('      mill 2D svg connect','programs/1%20machines/1.4%20ShopBot/mill%202D%20svg%20connect')
program_menu('      mill 3D stl','programs/1%20machines/1.4%20ShopBot/mill%203D%20stl')
program_label('   1.5 G-code')
program_menu('      mill 2D png','programs/1%20machines/1.5%20G-code/mill%202D%20png')
program_menu('      mill 2D svg','programs/1%20machines/1.5%20G-code/mill%202D%20svg')
program_label('2 frep')
program_menu('   gears','programs/2%20frep/gears')
program_menu('   lattice torus','programs/2%20frep/lattice%20torus')
program_menu('   smiley','programs/2%20frep/smiley')
program_label('image')
program_menu('   function','programs/image/function')
program_menu('   motion detect','programs/image/motion%20detect')
program_menu('   palette mask raster','programs/image/palette%20mask%20raster')
program_menu('   palette mask vector','programs/image/palette%20mask%20vector')
program_menu('   vectorize','programs/image/vectorize')
program_label('iterate')
program_menu('   z theta scan','programs/iterate/z%20theta%20scan')
program_label('math')
program_menu('   benchmark','programs/math/benchmark')
program_menu('   expressions','programs/math/expressions')
program_label('processes')
program_label('   cut')
program_label('      raster')
program_menu('         video','programs/processes/cut/raster/video')
program_label('   mill')
program_label('      raster')
program_menu('         2.5D','programs/processes/mill/raster/2.5D')
program_menu('         2D','programs/processes/mill/raster/2D')
program_label('variable')
program_menu('   text variables','programs/variable/text%20variables')

